#############################################################################
# Makefile for building: RiasBaixas
# Generated by qmake (2.01a) (Qt 4.8.1) on: Wed Dec 12 12:26:30 2012
# Project:  RiasBaixas.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile RiasBaixas.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = clang++ -fdiagnostics-fixit-info -g
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -Iinclude -I/usr/local/boost -I$(HOME)/NGL/include -I$(HOME)/SDL-2.0/include -I$(HOME)/SDL2_ttf-2.0/include -I/usr/X11R6/include -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L/usr/X11R6/lib64 -L$(HOME)/NGL/lib -l NGL -L$(HOME)/glew-1.9.0/lib -L/usr/local/lib -Wl,-rpath,/usr/local/lib -L$(HOME)/SDL-2.0/lib -lSDL2 -L$(HOME)/SDL2_ttf-2.0/lib -lSDL2_ttf -lQtOpenGL -lQtGui -lQtCore -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = bin/

####### Files

SOURCES       = src/SpeedBoat.cpp \
		src/Renderer.cpp \
		src/GameManager.cpp \
		src/Sea.cpp \
		src/Controller.cpp \
		src/Floating.cpp \
		src/PlayerControls.cpp \
		src/CameraManager.cpp \
		src/Object.cpp \
		src/SourceManager.cpp \
		src/ObjectManager.cpp \
		src/Diagonal.cpp \
		src/Horizontal.cpp \
		src/Vertical.cpp \
		src/ControllerManager.cpp \
		src/TXTParser.cpp \
		src/BSpherePE.cpp \
		src/Utilities.cpp 
OBJECTS       = bin/SpeedBoat.o \
		bin/Renderer.o \
		bin/GameManager.o \
		bin/Sea.o \
		bin/Controller.o \
		bin/Floating.o \
		bin/PlayerControls.o \
		bin/CameraManager.o \
		bin/Object.o \
		bin/SourceManager.o \
		bin/ObjectManager.o \
		bin/Diagonal.o \
		bin/Horizontal.o \
		bin/Vertical.o \
		bin/ControllerManager.o \
		bin/TXTParser.o \
		bin/BSpherePE.o \
		bin/Utilities.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		RiasBaixas.pro
QMAKE_TARGET  = RiasBaixas
DESTDIR       = 
TARGET        = RiasBaixas

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: RiasBaixas.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile RiasBaixas.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile RiasBaixas.pro

dist: 
	@$(CHK_DIR_EXISTS) bin/RiasBaixas1.0.0 || $(MKDIR) bin/RiasBaixas1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) bin/RiasBaixas1.0.0/ && $(COPY_FILE) --parents include/Renderer.h include/SpeedBoat.h include/Sea.h include/Controller.h include/Floating.h include/Stream.h include/Ramp.h include/PlayerControls.h include/CameraManager.h include/Object.h include/SourceManager.h include/ObjectManager.h include/Parser.h include/Diagonal.h include/PoliceBoat.h include/Horizontal.h include/Vertical.h include/ControllerManager.h include/TXTParser.h include/PhysicsEngine.h include/BSpherePE.h include/Utilities.h bin/RiasBaixas1.0.0/ && $(COPY_FILE) --parents src/SpeedBoat.cpp src/Renderer.cpp src/GameManager.cpp src/Sea.cpp src/Controller.cpp src/Floating.cpp src/PlayerControls.cpp src/CameraManager.cpp src/Object.cpp src/SourceManager.cpp src/ObjectManager.cpp src/Diagonal.cpp src/Horizontal.cpp src/Vertical.cpp src/ControllerManager.cpp src/TXTParser.cpp src/BSpherePE.cpp src/Utilities.cpp bin/RiasBaixas1.0.0/ && (cd `dirname bin/RiasBaixas1.0.0` && $(TAR) RiasBaixas1.0.0.tar RiasBaixas1.0.0 && $(COMPRESS) RiasBaixas1.0.0.tar) && $(MOVE) `dirname bin/RiasBaixas1.0.0`/RiasBaixas1.0.0.tar.gz . && $(DEL_FILE) -r bin/RiasBaixas1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

bin/SpeedBoat.o: src/SpeedBoat.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/SpeedBoat.o src/SpeedBoat.cpp

bin/Renderer.o: src/Renderer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/Renderer.o src/Renderer.cpp

bin/GameManager.o: src/GameManager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/GameManager.o src/GameManager.cpp

bin/Sea.o: src/Sea.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/Sea.o src/Sea.cpp

bin/Controller.o: src/Controller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/Controller.o src/Controller.cpp

bin/Floating.o: src/Floating.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/Floating.o src/Floating.cpp

bin/PlayerControls.o: src/PlayerControls.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/PlayerControls.o src/PlayerControls.cpp

bin/CameraManager.o: src/CameraManager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/CameraManager.o src/CameraManager.cpp

bin/Object.o: src/Object.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/Object.o src/Object.cpp

bin/SourceManager.o: src/SourceManager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/SourceManager.o src/SourceManager.cpp

bin/ObjectManager.o: src/ObjectManager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/ObjectManager.o src/ObjectManager.cpp

bin/Diagonal.o: src/Diagonal.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/Diagonal.o src/Diagonal.cpp

bin/Horizontal.o: src/Horizontal.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/Horizontal.o src/Horizontal.cpp

bin/Vertical.o: src/Vertical.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/Vertical.o src/Vertical.cpp

bin/ControllerManager.o: src/ControllerManager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/ControllerManager.o src/ControllerManager.cpp

bin/TXTParser.o: src/TXTParser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/TXTParser.o src/TXTParser.cpp

bin/BSpherePE.o: src/BSpherePE.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/BSpherePE.o src/BSpherePE.cpp

bin/Utilities.o: src/Utilities.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/Utilities.o src/Utilities.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

